ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

# Here lies some fine ideas for how to avoid rebuilding packages in
# new stack subprojects, such as those generated by the gidl
# tests. Unfortunately, there's no way to prevent stack from
# rebuilding dependencies pointed to by the `packages` stanza.

# STACK    ?= stack --work-dir $(ROOT_DIR)/.stack-work
# export STACK_ROOT := $(ROOT_DIR)/.stack-work
# $(info STACK=$(STACK))
# $(info STACK_ROOT=$(STACK_ROOT))
