# For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration.html

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-5.13

# Local packages, usually specified by relative directory name
packages:
- gec/
- gidl/
- ivory/ivory/
- ivory/ivory-artifact/
- ivory/ivory-backend-c/
- ivory/ivory-eval/
- ivory/ivory-examples/
- ivory/ivory-hw/
- ivory/ivory-model-check/
- ivory/ivory-opts/
- ivory/ivory-quickcheck/
- ivory/ivory-serialize/
- ivory/ivory-stdlib/
#- ivory-rtverification/rtv-example/
#- ivory-rtverification/rtv-lib/
- ivory-tower-posix/
- ivory-tower-stm32/ivory-bsp-stm32/
- ivory-tower-stm32/ivory-bsp-tests/
- ivory-tower-stm32/ivory-freertos-bindings/
- ivory-tower-stm32/tower-freertos-stm32/
- ivory-tower-stm32/tower-freertos-stm32-tests/
- ivory-tower-stm32/tower-echronos-stm32/
#- ivorylang-org/
#- smaccmpilot-org/
- smaccmpilot-stm32f4/src/ivory-geo/
- smaccmpilot-stm32f4/src/ivory-px4-hw/
- smaccmpilot-stm32f4/src/smaccm-comm-client/
- smaccmpilot-stm32f4/src/smaccm-comm-schema/smaccm-comm-schema-native/
- smaccmpilot-stm32f4/src/smaccm-comm-schema/smaccm-comm-schema-tower/
- smaccmpilot-stm32f4/src/smaccm-commsec/
- smaccmpilot-stm32f4/src/smaccm-datalink/
- smaccmpilot-stm32f4/src/smaccm-flight/
- smaccmpilot-stm32f4/src/smaccm-ins/
- tower/tower/
- tower/tower-aadl/
- tower/tower-config/
- tower/tower-hal/
- tower-camkes-odroid/
# estimator with relaxed version bounds; remove when pushed to Hackage
- location:
    git: https://github.com/GaloisInc/estimator.git
    commit: 4818515e8a05d7d9c54e51d7ac7fa21580336366
  extra-dep: true

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
  - base-compat-0.9.0
  - cipher-aes128-0.7.0.1
  - cpphs-1.19.3
  - curve25519-0.2.2
  - ed25519-donna-0.1.1
#  - estimator-1.1.0.2
  - exception-mtl-0.4
  - ghc-srcspan-plugin-0.2.1.0
  - language-c-quote-0.11.4
  - mainland-pretty-0.4.1.2
  - primitive-0.6.1.0
  - s-cargot-0.1.0.0
  - serialport-0.4.7
  - symbol-0.2.4

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

install-ghc: true

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
